version: '3'

services:
  mariadb:
    container_name: "mariadb"
    image: mariadb:10
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - TZ="Asia/Seoul"
    networks:
      - hihinakrock
networks:
  hihinakrock:
    external: true
