version: '3'

services:
  mariadb:
    container_name: "mariadb"
    build:
      context: .
#    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    environment:
      - TZ="Asia/Seoul"
      - MARIADB_ROOT_PASSWORD=12341234
      - MARIADB_USER=himina1227
      - MARIADB_PASSWORD=12341234
      - MARIADB_DATABASE=item
    networks:
      - hihinakrock
networks:
  hihinakrock:
    external: true
